general:
  technitium_url: "http://[::1]:5380"
  api_token: "token"
  isp_prefix_length: 56 #Must be 64 or smaller

zones:
  - "test.home.arpa"
  - "test2.home.arpa"

dns:
  ttl: 300 #Keep it small if your prefix changes frequently
  ptr: True #If set "True" it will updates every PTR Zone in Technitium with a GUA prefix as the name
